#version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: python main.py
    environment:
      - HOST=10.10.10.115
      - PORT=50005
      - DATABASE=MAXDB76
      - USERNAME=maximo
      - PASSWORD=maximo
      - DB_TYPE=db2
  app2:
    build: .
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    command: python main.py
    environment:
      - HOST=10.10.10.131
      - PORT=32298
      - DATABASE=ORCLPDB1
      - USERNAME=SYS
      - PASSWORD=zaq1xsW2
      - DB_TYPE=oracle